name: Sync hammad/milestone-4 to Staging

on:
  push:
    branches:
      - hammad/milestone-4 

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Configure SSH for GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure Git
        run: |
          git config --global user.name '${{ secrets.GIT_USER_NAME }}'
          git config --global user.email '${{ secrets.GIT_USER_EMAIL }}'

      - name: Push to Personal Repo's Staging Branch
        run: |
          git remote add personal git@github.com:HamzaAhad/construction-app-admin-v2.git
          git fetch personal
          git checkout -b staging personal/staging || git checkout staging  
          git merge hammad/milestone-4 --allow-unrelated-histories  # Merge the changes from the organizational repo
          git push personal staging --force  # Push to the staging branch in the personal repo
